# In the spirit of Organization, comments have been kept to a minimum. Please go to the Wiki for in-depth guidance

data-format: 'h2'
# Options: h2, sqlite, mysql (more coming eventually)

mysql:
  host: "127.0.0.1:3306"
  database: 'sldatabase'
  username: example
  password: elpmaxe


debug-mode: false
# Turn this on when you find a bug and try and cause the bug again.
# Then, report the bug on discord and/or github.
# You can report bugs without this, but the debug entries make my life easier.

config-version: 2.0