name: ServerLevels
version: '${version}'

main: us.to.midensthings.serverLevels.ServerLevels
api-version: '26.1.2'
load: POSTWORLD

dependencies:
  server:
    NouveauEnchanting:
      required: false
      join-classpath: true

permissions:
  serverlevels.commands.set:
    default: op
    description: Allows usage of server levels exp commands
  serverlevels.commands.add:
    default: op
    description: Allows usage of server levels level commands
  serverlevels.commands.remove:
    default: op
    description: Allows usage of server levels level commands
  serverlevels.commands.reload:
    default: op
    description: Allows usage of server levels level commands