name: ServerLevels
version: '${version}'

main: us.to.midensthings.serverLevels.ServerLevels
api-version: '26.1.2'
load: POSTWORLD

dependencies:
  server:
    NouveauEnchanting:
      required: false
      join-classpath: true
    ProjectKorra:
      required: false
      join-classpath: true
    MythicMobs:
      required: false
      join-classpath: true

permissions:
  serverlevels.commands.addsystem:
    default: op
    description: Allows usage of server levels addSystem command
  serverlevels.commands.removesystem:
    default: op
    description: Allows usage of server levels removeSystem command
  serverlevels.commands.set:
    default: op
    description: Allows usage of server levels set commands
  serverlevels.commands.add:
    default: op
    description: Allows usage of server levels add commands
  serverlevels.commands.remove:
    default: op
    description: Allows usage of server levels remove commands
  serverlevels.commands.reload:
    default: op
    description: Allows usage of server levels reload command